version: '3.1'
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  node-tests:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - "mongo"


volumes:
  mongodb: